baseURL = 'https://1atk.space/'
relativeURLs = false
canonifyURLs = true
title = "1atk's personal blog"
theme = "hugo-theme-stack"
languageCode = "zh-cn"

[params]
    mainSections = ["posts"]
    sidebar = { avatar = "profile.jpg", title = "1atk", subtitle = "学点什么，想点什么，写点什么。\n\ncongwithsilent@gmail.com" }
    
    # 侧边栏小工具配置
    [params.widgets]
        page = [
            { type = "toc" } # 开启目录小工具
        ]
        homepage = [
            { type = "search" },
            { type = "archives" }
        ]

    # 社交链接
    [[params.social]]
        name = "GitHub"
        icon = "github"
        url = "https://github.com/onweb1atk"
    [[params.social]]
        name = "Email"
        icon = "mail"
        url = "mailto:congwithsilent@gmail.com"

    # 文章页配置
    [params.article]
        math = false
        toc = true
        readingTime = true

    # 颜色模式
    [params.colorScheme]
        toggle = true
        default = "auto"

    # 暂未配置评论服务，避免文章页出现空评论卡片
    [params.comments]
        enabled = false

[menu]
    [[menu.main]]
        identifier = "home"
        name = "首页"
        url = "/"
        weight = 10
    [[menu.main]]
        identifier = "posts"
        name = "文章"
        url = "/posts"
        weight = 20
    [[menu.main]]
        identifier = "about"
        name = "关于"
        url = "/about"
        weight = 30
    [[menu.main]]
        identifier = "archives"
        name = "归档"
        url = "/archives"
        weight = 40
    [[menu.main]]
        identifier = "search"
        name = "搜索"
        url = "/search"
        weight = 50

[outputs]
    home = ["HTML", "RSS"]
